"""
Forensic Report Generator using Llama 3.1-8B
Generates professional forensic reports from image analysis results
"""

import logging
from pathlib import Path
from typing import List, Dict, Any
from datetime import datetime
from dataclasses import dataclass

from llm.ollama_client import get_ollama_client

logger = logging.getLogger(__name__)


FORENSIC_SYSTEM_PROMPT = """You are an expert forensic analyst generating professional investigation reports.

Your reports should be:
1. **Objective** - Present facts without speculation
2. **Detailed** - Include all relevant observations
3. **Structured** - Use clear sections and formatting
4. **Professional** - Use appropriate forensic terminology
5. **Actionable** - Highlight suspicious or notable findings

Focus on:
- Physical evidence visible in images
- Persons present and their characteristics
- Objects of forensic interest (weapons, vehicles, etc.)
- Scene type and environmental context
- Potential investigative leads

Use professional language suitable for law enforcement and legal proceedings."""


@dataclass
class ImageAnalysisReport:
    """Forensic report for image analysis"""
    report_id: str
    case_id: str
    generated_at: datetime
    report_text: str
    summary: str
    key_findings: List[str]
    suspicious_items: List[str]
    recommended_actions: List[str]
    confidence_level: str
    metadata: Dict[str, Any]
    
    def to_dict(self) -> Dict:
        return {
            "report_id": self.report_id,
            "case_id": self.case_id,
            "generated_at": self.generated_at.isoformat(),
            "report_text": self.report_text,
            "summary": self.summary,
            "key_findings": self.key_findings,
            "suspicious_items": self.suspicious_items,
            "recommended_actions": self.recommended_actions,
            "confidence_level": self.confidence_level,
            "metadata": self.metadata
        }
    
    def to_markdown(self) -> str:
        """Format report as Markdown"""
        md = f"""# Forensic Image Analysis Report
**Report ID**: {self.report_id}  
**Case ID**: {self.case_id}  
**Generated**: {self.generated_at.strftime('%Y-%m-%d %H:%M:%S')}  
**Confidence**: {self.confidence_level}

---

## Executive Summary
{self.summary}

---

## Detailed Analysis
{self.report_text}

---

## Key Findings
"""
        for finding in self.key_findings:
            md += f"- {finding}\n"
        
        if self.suspicious_items:
            md += "\n---\n\n## ⚠️ Suspicious Items\n"
            for item in self.suspicious_items:
                md += f"- {item}\n"
        
        if self.recommended_actions:
            md += "\n---\n\n## Recommended Actions\n"
            for action in self.recommended_actions:
                md += f"- {action}\n"
        
        md += f"\n---\n\n*Report generated by AI-powered forensic analysis system*"
        
        return md


class ForensicReportGenerator:
    """
    Generate forensic reports from image analysis using Llama 3.1-8B
    
    Features:
    - Single image reports
    - Batch image analysis reports
    - Case summary reports
    - Pattern detection across multiple images
    """
    
    def __init__(self, model: str = "llama3.1:8b"):
        """
        Initialize report generator
        
        Args:
            model: Ollama model to use
        """
        self.llm = get_ollama_client(model=model)
        self.model = model
        
        logger.info(f"Forensic Report Generator initialized (model: {model})")
    
    def is_available(self) -> bool:
        """Check if LLM is available"""
        return self.llm.is_available() and self.llm.is_model_available()
    
    def generate_single_image_report(
        self,
        image_result: Dict[str, Any],
        detail_level: str = "detailed"
    ) -> ImageAnalysisReport:
        """
        Generate report for a single image analysis result
        
        Args:
            image_result: EnhancedImageResult as dict
            detail_level: "brief", "detailed", or "comprehensive"
        
        Returns:
            ImageAnalysisReport object
        """
        # Build prompt from image analysis data
        prompt = self._build_single_image_prompt(image_result, detail_level)
        
        # Generate report
        response = self.llm.generate(
            prompt=prompt,
            system=FORENSIC_SYSTEM_PROMPT,
            temperature=0.3,  # Lower temperature for consistent reports
            max_tokens=2000 if detail_level == "comprehensive" else 1000
        )
        
        if not response.success:
            logger.error(f"Failed to generate report: {response.error}")
            return self._create_fallback_report(image_result)
        
        # Parse response and extract structured data
        report_data = self._parse_report_response(response.text)
        
        # Create report object
        report = ImageAnalysisReport(
            report_id=f"IMG_REPORT_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            case_id=image_result.get('case_id', 'UNKNOWN'),
            generated_at=datetime.now(),
            report_text=report_data['full_text'],
            summary=report_data['summary'],
            key_findings=report_data['key_findings'],
            suspicious_items=report_data['suspicious_items'],
            recommended_actions=report_data['recommended_actions'],
            confidence_level=report_data['confidence'],
            metadata={
                "model": self.model,
                "image_id": image_result.get('image_id'),
                "file_path": image_result.get('file_path'),
                "generation_time": response.total_duration,
                "detail_level": detail_level
            }
        )
        
        return report
    
    def generate_batch_report(
        self,
        image_results: List[Dict[str, Any]],
        case_id: str
    ) -> ImageAnalysisReport:
        """
        Generate comprehensive report for multiple images
        
        Args:
            image_results: List of EnhancedImageResult dicts
            case_id: Case identifier
        
        Returns:
            ImageAnalysisReport combining all images
        """
        # Build batch analysis prompt
        prompt = self._build_batch_prompt(image_results, case_id)
        
        # Generate report
        response = self.llm.generate(
            prompt=prompt,
            system=FORENSIC_SYSTEM_PROMPT,
            temperature=0.3,
            max_tokens=4000  # Longer for batch reports
        )
        
        if not response.success:
            logger.error(f"Failed to generate batch report: {response.error}")
            return self._create_fallback_batch_report(image_results, case_id)
        
        # Parse response
        report_data = self._parse_report_response(response.text)
        
        # Create report
        report = ImageAnalysisReport(
            report_id=f"BATCH_REPORT_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            case_id=case_id,
            generated_at=datetime.now(),
            report_text=report_data['full_text'],
            summary=report_data['summary'],
            key_findings=report_data['key_findings'],
            suspicious_items=report_data['suspicious_items'],
            recommended_actions=report_data['recommended_actions'],
            confidence_level=report_data['confidence'],
            metadata={
                "model": self.model,
                "image_count": len(image_results),
                "generation_time": response.total_duration
            }
        )
        
        return report
    
    def _build_single_image_prompt(
        self,
        image_result: Dict[str, Any],
        detail_level: str
    ) -> str:
        """Build prompt for single image report"""
        
        # Extract key information
        file_name = Path(image_result.get('file_path', '')).name
        blip_desc = image_result.get('blip_description', 'No description available')
        scene_type = image_result.get('blip_scene_type', 'unknown')
        
        # Object detections
        objects = image_result.get('detected_objects', {})
        obj_list = []
        for obj_class, obj_data in objects.items():
            count = obj_data.get('count', 0)
            obj_list.append(f"{count}x {obj_class}")
        
        # Forensic summary
        forensic = image_result.get('forensic_summary', {})
        has_people = forensic.get('has_people', False)
        has_weapons = forensic.get('has_weapons', False)
        has_vehicles = forensic.get('has_vehicles', False)
        
        # Face information
        face_count = image_result.get('face_count', 0)
        faces = image_result.get('faces', [])
        
        prompt = f"""Generate a forensic analysis report for the following image:

**Image**: {file_name}
**Scene Description**: {blip_desc}
**Scene Type**: {scene_type}

**Detected Objects**:
{chr(10).join(f"- {obj}" for obj in obj_list) if obj_list else "- None detected"}

**People & Faces**:
- People detected: {"Yes" if has_people else "No"}
- Faces identified: {face_count}
"""
        
        if faces:
            prompt += "\n**Face Details**:\n"
            for i, face in enumerate(faces, 1):
                gender = face.get('gender', 'unknown')
                age = face.get('age', 'unknown')
                emotion = face.get('emotion', 'unknown')
                prompt += f"  Face {i}: {gender}, ~{age} years, emotion: {emotion}\n"
        
        prompt += f"""
**Forensic Indicators**:
- Weapons present: {"⚠️ YES" if has_weapons else "No"}
- Vehicles present: {"Yes" if has_vehicles else "No"}

---

Generate a {detail_level} forensic report analyzing this image. Structure your response as:

1. **SUMMARY**: Brief 2-3 sentence overview
2. **DETAILED ANALYSIS**: Comprehensive description of all visual evidence
3. **KEY FINDINGS**: Bullet points of important observations
4. **SUSPICIOUS ITEMS**: Any weapons, contraband, or concerning elements (if any)
5. **RECOMMENDED ACTIONS**: Investigative steps to take (if needed)
6. **CONFIDENCE**: Overall confidence in analysis (High/Medium/Low)

Focus on facts and observable evidence. Be objective and professional."""

        return prompt
    
    def _build_batch_prompt(
        self,
        image_results: List[Dict[str, Any]],
        case_id: str
    ) -> str:
        """Build prompt for batch image report"""
        
        prompt = f"""Generate a comprehensive forensic analysis report for Case {case_id}.

**Total Images Analyzed**: {len(image_results)}

---

**Image Summaries**:

"""
        
        for i, result in enumerate(image_results, 1):
            file_name = Path(result.get('file_path', '')).name
            blip_desc = result.get('blip_description', 'No description')
            obj_count = result.get('object_count', 0)
            face_count = result.get('face_count', 0)
            
            forensic = result.get('forensic_summary', {})
            has_weapons = forensic.get('has_weapons', False)
            has_vehicles = forensic.get('has_vehicles', False)
            
            prompt += f"""
Image {i}: {file_name}
- Description: {blip_desc}
- Objects: {obj_count}, Faces: {face_count}
- Weapons: {"⚠️ YES" if has_weapons else "No"}, Vehicles: {"Yes" if has_vehicles else "No"}
"""
        
        prompt += """

---

Generate a comprehensive forensic case report analyzing all images collectively. Include:

1. **EXECUTIVE SUMMARY**: Overview of the entire case
2. **IMAGE-BY-IMAGE ANALYSIS**: Key observations from each image
3. **PATTERNS & CONNECTIONS**: Recurring elements, people, or locations
4. **SUSPICIOUS FINDINGS**: Weapons, contraband, or concerning evidence
5. **TIMELINE** (if determinable): Chronological sequence of events
6. **KEY PERSONS**: Recurring individuals across images
7. **RECOMMENDED ACTIONS**: Priority investigative steps
8. **CONFIDENCE ASSESSMENT**: Overall reliability of analysis

Be thorough, objective, and highlight forensically significant details."""
        
        return prompt
    
    def _parse_report_response(self, text: str) -> Dict[str, Any]:
        """Parse LLM response into structured report components"""
        
        # Simple parsing - look for sections
        lines = text.split('\n')
        
        summary = ""
        key_findings = []
        suspicious_items = []
        recommended_actions = []
        confidence = "Medium"
        
        current_section = None
        
        for line in lines:
            line_lower = line.lower().strip()
            
            # Detect sections
            if 'summary' in line_lower and ':' in line:
                current_section = 'summary'
                summary = line.split(':', 1)[1].strip() if ':' in line else ""
            elif 'key finding' in line_lower:
                current_section = 'findings'
            elif 'suspicious' in line_lower:
                current_section = 'suspicious'
            elif 'recommended' in line_lower or 'action' in line_lower:
                current_section = 'actions'
            elif 'confidence' in line_lower and ':' in line:
                confidence_part = line.split(':', 1)[1].strip()
                for level in ['High', 'Medium', 'Low']:
                    if level.lower() in confidence_part.lower():
                        confidence = level
                        break
            
            # Collect content
            elif line.strip().startswith('-') or line.strip().startswith('•'):
                content = line.strip()[1:].strip()
                if content:
                    if current_section == 'findings':
                        key_findings.append(content)
                    elif current_section == 'suspicious':
                        suspicious_items.append(content)
                    elif current_section == 'actions':
                        recommended_actions.append(content)
            
            # Continue summary if it's multi-line
            elif current_section == 'summary' and line.strip() and not ':' in line:
                summary += " " + line.strip()
        
        # Fallback: if no structured parsing worked, extract from full text
        if not summary:
            # Use first 200 chars as summary
            summary = text[:200].strip() + "..." if len(text) > 200 else text.strip()
        
        if not key_findings:
            key_findings = ["Comprehensive visual analysis completed", "All observable evidence documented"]
        
        return {
            'full_text': text,
            'summary': summary,
            'key_findings': key_findings,
            'suspicious_items': suspicious_items,
            'recommended_actions': recommended_actions,
            'confidence': confidence
        }
    
    def _create_fallback_report(self, image_result: Dict[str, Any]) -> ImageAnalysisReport:
        """Create basic report when LLM fails"""
        file_name = Path(image_result.get('file_path', '')).name
        blip_desc = image_result.get('blip_description', 'No description available')
        
        return ImageAnalysisReport(
            report_id=f"FALLBACK_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            case_id=image_result.get('case_id', 'UNKNOWN'),
            generated_at=datetime.now(),
            report_text=f"Basic analysis: {blip_desc}",
            summary=f"Image {file_name} analyzed with automated tools",
            key_findings=[blip_desc],
            suspicious_items=[],
            recommended_actions=["Manual review recommended"],
            confidence_level="Low",
            metadata={"fallback": True}
        )
    
    def _create_fallback_batch_report(
        self,
        image_results: List[Dict[str, Any]],
        case_id: str
    ) -> ImageAnalysisReport:
        """Create basic batch report when LLM fails"""
        
        return ImageAnalysisReport(
            report_id=f"FALLBACK_BATCH_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            case_id=case_id,
            generated_at=datetime.now(),
            report_text=f"Analyzed {len(image_results)} images for case {case_id}",
            summary=f"Batch analysis of {len(image_results)} images completed",
            key_findings=[f"Processed {len(image_results)} images successfully"],
            suspicious_items=[],
            recommended_actions=["Manual review of LLM-generated reports recommended"],
            confidence_level="Low",
            metadata={"fallback": True, "image_count": len(image_results)}
        )


# Singleton instance
_report_generator = None


def get_report_generator(model: str = "llama3.1:8b") -> ForensicReportGenerator:
    """Get singleton report generator instance"""
    global _report_generator
    
    if _report_generator is None:
        _report_generator = ForensicReportGenerator(model=model)
    
    return _report_generator
