"""
Heuristics Rule Engine for UFDR Analysis
Automatically detects suspicious patterns and generates alerts

Features:
- Configurable rule sets for different threat patterns
- Real-time alert generation
- Confidence scoring
- Alert lifecycle management
"""

import re
import json
import uuid
from datetime import datetime
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field, asdict
from enum import Enum
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class AlertSeverity(Enum):
    """Alert severity levels"""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class AlertStatus(Enum):
    """Alert lifecycle status"""
    NEW = "new"
    TRIAGED = "triaged"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"
    FALSE_POSITIVE = "false_positive"
    ESCALATED = "escalated"


class RuleCategory(Enum):
    """Categories of heuristic rules"""
    CRYPTOCURRENCY = "cryptocurrency"
    FOREIGN_CONTACT = "foreign_contact"
    WEAPONS = "weapons"
    DRUGS = "drugs"
    SUSPICIOUS_KEYWORDS = "suspicious_keywords"
    VOLUME_ANOMALY = "volume_anomaly"
    TIME_PATTERN = "time_pattern"
    LOCATION_PATTERN = "location_pattern"
    COMMUNICATION_PATTERN = "communication_pattern"
    FINANCIAL = "financial"


@dataclass
class Alert:
    """Alert generated by heuristic rules"""
    alert_id: str
    case_id: str
    rule_id: str
    rule_name: str
    category: RuleCategory
    severity: AlertSeverity
    status: AlertStatus
    confidence: float  # 0.0 to 1.0
    title: str
    description: str
    evidence: Dict[str, Any]
    entity_id: Optional[str] = None
    entity_type: Optional[str] = None  # message, call, media, etc.
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)
    assigned_to: Optional[str] = None
    notes: List[str] = field(default_factory=list)
    tags: List[str] = field(default_factory=list)
    
    def to_dict(self) -> Dict:
        """Convert to dictionary"""
        data = asdict(self)
        data['category'] = self.category.value
        data['severity'] = self.severity.value
        data['status'] = self.status.value
        data['created_at'] = self.created_at.isoformat()
        data['updated_at'] = self.updated_at.isoformat()
        return data


@dataclass
class HeuristicRule:
    """A heuristic detection rule"""
    rule_id: str
    name: str
    description: str
    category: RuleCategory
    severity: AlertSeverity
    pattern: str  # Regex pattern or keyword list
    confidence: float
    enabled: bool = True
    metadata: Dict[str, Any] = field(default_factory=dict)


class HeuristicRuleEngine:
    """
    Rule engine for automated pattern detection and alert generation
    """
    
    def __init__(self, case_id: str):
        """
        Initialize rule engine
        
        Args:
            case_id: Case identifier
        """
        self.case_id = case_id
        self.rules = self._load_default_rules()
        self.alerts: List[Alert] = []
        
        logger.info(f"Initialized heuristic engine for case: {case_id}")
    
    def _load_default_rules(self) -> List[HeuristicRule]:
        """Load default detection rules"""
        rules = []
        
        # Cryptocurrency patterns
        rules.append(HeuristicRule(
            rule_id="CRYPTO_001",
            name="Bitcoin Address Detection",
            description="Detects Bitcoin wallet addresses in messages",
            category=RuleCategory.CRYPTOCURRENCY,
            severity=AlertSeverity.HIGH,
            pattern=r'\b[13][a-km-zA-HJ-NP-Z1-9]{25,34}\b',
            confidence=0.9
        ))
        
        rules.append(HeuristicRule(
            rule_id="CRYPTO_002",
            name="Ethereum Address Detection",
            description="Detects Ethereum wallet addresses",
            category=RuleCategory.CRYPTOCURRENCY,
            severity=AlertSeverity.HIGH,
            pattern=r'\b0x[a-fA-F0-9]{40}\b',
            confidence=0.9
        ))
        
        rules.append(HeuristicRule(
            rule_id="CRYPTO_003",
            name="Crypto Keywords",
            description="Detects cryptocurrency-related keywords",
            category=RuleCategory.CRYPTOCURRENCY,
            severity=AlertSeverity.MEDIUM,
            pattern=r'\b(bitcoin|btc|ethereum|eth|crypto|wallet|blockchain|mining|satoshi|exchange|binance|coinbase)\b',
            confidence=0.7
        ))
        
        # Foreign contact patterns
        rules.append(HeuristicRule(
            rule_id="FOREIGN_001",
            name="Non-Indian Phone Numbers",
            description="Detects communications with foreign phone numbers",
            category=RuleCategory.FOREIGN_CONTACT,
            severity=AlertSeverity.MEDIUM,
            pattern=r'\+(?!91)[0-9]{1,3}[0-9]{6,14}',
            confidence=0.8
        ))
        
        # Weapons keywords
        rules.append(HeuristicRule(
            rule_id="WEAPON_001",
            name="Weapons Keywords",
            description="Detects weapons-related keywords",
            category=RuleCategory.WEAPONS,
            severity=AlertSeverity.CRITICAL,
            pattern=r'\b(gun|pistol|rifle|ak-47|ak47|weapon|explosive|bomb|grenade|ammunition|firearm)\b',
            confidence=0.85
        ))
        
        # Drugs keywords
        rules.append(HeuristicRule(
            rule_id="DRUG_001",
            name="Drugs Keywords",
            description="Detects drug-related keywords",
            category=RuleCategory.DRUGS,
            severity=AlertSeverity.CRITICAL,
            pattern=r'\b(heroin|cocaine|meth|mdma|cannabis|marijuana|dealer|supply|package|shipment)\b',
            confidence=0.85
        ))
        
        # Financial suspicious keywords
        rules.append(HeuristicRule(
            rule_id="FINANCIAL_001",
            name="Money Laundering Keywords",
            description="Detects potential money laundering indicators",
            category=RuleCategory.FINANCIAL,
            severity=AlertSeverity.HIGH,
            pattern=r'\b(hawala|money\s+transfer|cash\s+payment|wire\s+transfer|offshore|swiss\s+bank|black\s+money)\b',
            confidence=0.8
        ))
        
        # Suspicious communication patterns
        rules.append(HeuristicRule(
            rule_id="COMM_001",
            name="Encrypted App Usage",
            description="Detects usage of encrypted messaging apps",
            category=RuleCategory.COMMUNICATION_PATTERN,
            severity=AlertSeverity.MEDIUM,
            pattern=r'\b(signal|telegram|wickr|threema|encrypted)\b',
            confidence=0.6
        ))
        
        return rules
    
    def add_rule(self, rule: HeuristicRule):
        """Add a custom rule"""
        self.rules.append(rule)
        logger.info(f"Added rule: {rule.name}")
    
    def remove_rule(self, rule_id: str):
        """Remove a rule"""
        self.rules = [r for r in self.rules if r.rule_id != rule_id]
        logger.info(f"Removed rule: {rule_id}")
    
    def enable_rule(self, rule_id: str):
        """Enable a rule"""
        for rule in self.rules:
            if rule.rule_id == rule_id:
                rule.enabled = True
                logger.info(f"Enabled rule: {rule_id}")
                break
    
    def disable_rule(self, rule_id: str):
        """Disable a rule"""
        for rule in self.rules:
            if rule.rule_id == rule_id:
                rule.enabled = False
                logger.info(f"Disabled rule: {rule_id}")
                break
    
    def analyze_message(self, message: Dict) -> List[Alert]:
        """
        Analyze a message against all rules
        
        Args:
            message: Message dictionary with text, from, to, etc.
            
        Returns:
            List of generated alerts
        """
        alerts = []
        text = message.get('text', '').lower()
        
        for rule in self.rules:
            if not rule.enabled:
                continue
            
            # Check if pattern matches
            matches = re.findall(rule.pattern, text, re.IGNORECASE)
            
            if matches:
                alert = Alert(
                    alert_id=str(uuid.uuid4()),
                    case_id=self.case_id,
                    rule_id=rule.rule_id,
                    rule_name=rule.name,
                    category=rule.category,
                    severity=rule.severity,
                    status=AlertStatus.NEW,
                    confidence=rule.confidence,
                    title=f"{rule.name} - Match Found",
                    description=f"Rule '{rule.name}' triggered: {rule.description}",
                    evidence={
                        'message_id': message.get('id'),
                        'text_snippet': text[:200],
                        'matches': matches[:5],  # First 5 matches
                        'from': message.get('from'),
                        'to': message.get('to'),
                        'timestamp': message.get('timestamp'),
                        'app': message.get('app')
                    },
                    entity_id=message.get('id'),
                    entity_type='message',
                    tags=[rule.category.value]
                )
                
                alerts.append(alert)
                self.alerts.append(alert)
                
                logger.info(f"Alert generated: {rule.name} for message {message.get('id')}")
        
        return alerts
    
    def analyze_call(self, call: Dict) -> List[Alert]:
        """
        Analyze a call record against rules
        
        Args:
            call: Call dictionary
            
        Returns:
            List of generated alerts
        """
        alerts = []
        number = call.get('number', '')
        
        # Check foreign number rule
        for rule in self.rules:
            if not rule.enabled or rule.category != RuleCategory.FOREIGN_CONTACT:
                continue
            
            if re.match(rule.pattern, number):
                alert = Alert(
                    alert_id=str(uuid.uuid4()),
                    case_id=self.case_id,
                    rule_id=rule.rule_id,
                    rule_name=rule.name,
                    category=rule.category,
                    severity=rule.severity,
                    status=AlertStatus.NEW,
                    confidence=rule.confidence,
                    title=f"{rule.name} - Foreign Contact",
                    description=f"Call to/from foreign number detected",
                    evidence={
                        'call_id': call.get('id'),
                        'number': number,
                        'direction': call.get('direction'),
                        'duration': call.get('duration'),
                        'timestamp': call.get('timestamp')
                    },
                    entity_id=call.get('id'),
                    entity_type='call',
                    tags=['foreign_contact']
                )
                
                alerts.append(alert)
                self.alerts.append(alert)
        
        return alerts
    
    def analyze_volume_anomaly(self, 
                               entity_type: str, 
                               counts_by_hour: Dict[int, int]) -> List[Alert]:
        """
        Detect volume anomalies (e.g., sudden spike in messages)
        
        Args:
            entity_type: Type of entity (messages, calls, etc.)
            counts_by_hour: Dictionary mapping hour to count
            
        Returns:
            List of alerts for anomalies
        """
        alerts = []
        
        # Simple threshold-based anomaly detection
        values = list(counts_by_hour.values())
        if not values:
            return alerts
        
        avg = sum(values) / len(values)
        max_count = max(values)
        
        # Alert if max is 3x average
        if max_count > avg * 3 and max_count > 10:
            alert = Alert(
                alert_id=str(uuid.uuid4()),
                case_id=self.case_id,
                rule_id="VOLUME_001",
                rule_name="Volume Spike Detected",
                category=RuleCategory.VOLUME_ANOMALY,
                severity=AlertSeverity.MEDIUM,
                status=AlertStatus.NEW,
                confidence=0.7,
                title=f"Unusual {entity_type} Volume",
                description=f"Detected {max_count} {entity_type} in one hour (avg: {avg:.1f})",
                evidence={
                    'entity_type': entity_type,
                    'max_count': max_count,
                    'average': avg,
                    'counts_by_hour': counts_by_hour
                },
                tags=['volume_anomaly']
            )
            
            alerts.append(alert)
            self.alerts.append(alert)
        
        return alerts
    
    def analyze_time_pattern(self, 
                            timestamps: List[datetime]) -> List[Alert]:
        """
        Detect suspicious time patterns (e.g., late night activity)
        
        Args:
            timestamps: List of activity timestamps
            
        Returns:
            List of alerts
        """
        alerts = []
        
        # Count late night activity (1 AM - 5 AM)
        late_night_count = sum(
            1 for ts in timestamps 
            if 1 <= ts.hour <= 5
        )
        
        if late_night_count > 20:  # More than 20 late night activities
            alert = Alert(
                alert_id=str(uuid.uuid4()),
                case_id=self.case_id,
                rule_id="TIME_001",
                rule_name="Late Night Activity Pattern",
                category=RuleCategory.TIME_PATTERN,
                severity=AlertSeverity.MEDIUM,
                status=AlertStatus.NEW,
                confidence=0.6,
                title="Unusual Late Night Activity",
                description=f"Detected {late_night_count} activities between 1 AM - 5 AM",
                evidence={
                    'late_night_count': late_night_count,
                    'total_activities': len(timestamps)
                },
                tags=['time_pattern', 'late_night']
            )
            
            alerts.append(alert)
            self.alerts.append(alert)
        
        return alerts
    
    def get_alerts_by_severity(self, severity: AlertSeverity) -> List[Alert]:
        """Get alerts filtered by severity"""
        return [a for a in self.alerts if a.severity == severity]
    
    def get_alerts_by_status(self, status: AlertStatus) -> List[Alert]:
        """Get alerts filtered by status"""
        return [a for a in self.alerts if a.status == status]
    
    def get_alerts_by_category(self, category: RuleCategory) -> List[Alert]:
        """Get alerts filtered by category"""
        return [a for a in self.alerts if a.category == category]
    
    def update_alert_status(self, alert_id: str, new_status: AlertStatus, note: Optional[str] = None):
        """Update alert status"""
        for alert in self.alerts:
            if alert.alert_id == alert_id:
                alert.status = new_status
                alert.updated_at = datetime.now()
                if note:
                    alert.notes.append(f"{datetime.now().isoformat()}: {note}")
                logger.info(f"Updated alert {alert_id} to status: {new_status.value}")
                break
    
    def assign_alert(self, alert_id: str, investigator: str):
        """Assign alert to an investigator"""
        for alert in self.alerts:
            if alert.alert_id == alert_id:
                alert.assigned_to = investigator
                alert.status = AlertStatus.TRIAGED
                alert.updated_at = datetime.now()
                logger.info(f"Assigned alert {alert_id} to {investigator}")
                break
    
    def export_alerts(self, output_file: str):
        """Export alerts to JSON file"""
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(
                [alert.to_dict() for alert in self.alerts],
                f,
                indent=2,
                ensure_ascii=False
            )
        logger.info(f"Exported {len(self.alerts)} alerts to {output_file}")
    
    def get_summary(self) -> Dict:
        """Get summary of alerts"""
        summary = {
            'total_alerts': len(self.alerts),
            'by_severity': {},
            'by_status': {},
            'by_category': {},
        }
        
        for severity in AlertSeverity:
            count = len(self.get_alerts_by_severity(severity))
            summary['by_severity'][severity.value] = count
        
        for status in AlertStatus:
            count = len(self.get_alerts_by_status(status))
            summary['by_status'][status.value] = count
        
        for category in RuleCategory:
            count = len(self.get_alerts_by_category(category))
            summary['by_category'][category.value] = count
        
        return summary


# Example usage
if __name__ == "__main__":
    # Initialize engine
    engine = HeuristicRuleEngine(case_id="CASE_2024_001")
    
    # Analyze a suspicious message
    message = {
        'id': 'MSG123',
        'text': 'Meet at midnight. Bring the bitcoin wallet address: 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
        'from': '+919876543210',
        'to': '+447911123456',
        'timestamp': '2024-01-15 23:30:00',
        'app': 'WhatsApp'
    }
    
    alerts = engine.analyze_message(message)
    
    print(f"Generated {len(alerts)} alerts:")
    for alert in alerts:
        print(f"  - {alert.severity.value.upper()}: {alert.title}")
    
    # Get summary
    summary = engine.get_summary()
    print(f"\nAlert Summary:")
    print(json.dumps(summary, indent=2))
    
    # Export alerts
    engine.export_alerts("data/alerts/case_alerts.json")